#!/usr/bin/env python3
import argparse
import os
import pwd
import sys

from kilnr_retention import cleanup


def main():
    parser = argparse.ArgumentParser(description='Apply configured completed-build retention')
    parser.add_argument('--dry-run', action='store_true', help='show candidates without changing builds or Git refs')
    parser.add_argument('--project', help='limit cleanup to one project')
    args = parser.parse_args()
    if os.geteuid() == 0:
        os.execv("/usr/sbin/runuser", ["runuser", "-u", "kilnr", "--", "/usr/local/libexec/kilnr/cleanup", *sys.argv[1:]])
    if pwd.getpwuid(os.geteuid()).pw_name not in ('root', 'kilnr'):
        parser.error('must run as root or kilnr')
    try:
        return cleanup(project=args.project, dry_run=args.dry_run)
    except (OSError, ValueError) as exc:
        print(f'kilnr cleanup: {exc}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
